### ISSUE TITLE
MojiraBot fails to resolve a request if the original message has been deleted

### ISSUE THREAD

**Issue by violine1101** [mojira/mojira-discord-bot#59]
When trying to resolve a request whose message no longer exists (for instance because it has been delted while MojiraBot was down), the following error occurs:
```
(node:3479) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Message
    at item.request.gen.end (.../node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
    at then (.../node_modules/snekfetch/src/index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:3479) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3479) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
and nothing happens.

**Expected:** Simply delete the request when the message no longer exists.

**Comment by NeunEinser** [comment]
I think this can only happen when the message was deleted during a downtime.
I tested it in java-requests and it did indeed delete the internal message when I deleted mine.

**Comment by SPGoding** [comment]
Or when you delete a request posted before last restart, since that request is not fetched.
